apiVersion: v1
kind: PersistentVolume
metadata:
  name: sentiment-data-pv
  labels:
    app: sentiment-analysis
    environment: production
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast-ssd
  hostPath:
    path: /data/sentiment-analysis/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sentiment-cache-pv
  labels:
    app: sentiment-analysis
    environment: production
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast-ssd
  hostPath:
    path: /data/sentiment-analysis/cache
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sentiment-backups-pv
  labels:
    app: sentiment-analysis
    environment: production
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast-ssd
  hostPath:
    path: /data/sentiment-analysis/backups
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sentiment-results-pv
  labels:
    app: sentiment-analysis
    environment: production
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast-ssd
  hostPath:
    path: /data/sentiment-analysis/results
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentiment-data-pvc
  namespace: sentiment-analysis
  labels:
    app: sentiment-analysis
    environment: production
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentiment-cache-pvc
  namespace: sentiment-analysis
  labels:
    app: sentiment-analysis
    environment: production
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentiment-backups-pvc
  namespace: sentiment-analysis
  labels:
    app: sentiment-analysis
    environment: production
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentiment-results-pvc
  namespace: sentiment-analysis
  labels:
    app: sentiment-analysis
    environment: production
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 10Gi
