apiVersion: v1
kind: Secret
metadata:
  name: sentiment-secrets
  namespace: sentiment-analysis
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  API_KEY: eW91ci1zZWN1cmUtYXBpLWtleQ==  # your-secure-api-key
  SENTRY_DSN: eW91ci1zZW50cnktZHNu  # your-sentry-dsn
  CORS_ORIGINS: aHR0cHM6Ly95b3VyLWRvbWFpbi5jb20=  # https://your-domain.com
  RATE_LIMIT: MTAw  # 100
