apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-service
  namespace: sentiment-analysis
  labels:
    app: sentiment-analysis
spec:
  selector:
    app: sentiment-analysis
  ports:
  - name: mcp
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: api
    port: 8002
    targetPort: 8002
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: sentiment-analysis
  labels:
    app: ollama
spec:
  selector:
    app: ollama
  ports:
  - name: ollama
    port: 11434
    targetPort: 11434
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: sentiment-analysis
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP
